import { Market1Endpoints } from "./__db__/market-1";
import { RelatedProductsEndpoints } from "./__db__/related-products";
import { ShopEndpoints } from "./__db__/shop";
import { UsersEndpoints } from "./__db__/users";
import { TicketsEndpoints } from "./__db__/ticket";
import { UserOrders1Endpoints } from "./__db__/orders";
import { UserAddressEndpoints } from "./__db__/address";
import { ProductsEndpoints } from "./__db__/products";
import { LayoutEndpoints } from "./__db__/layout";
import { CartEndpoints } from "./__db__/cart";
export const MockEndPoints = Mock => {
  Market1Endpoints(Mock);
  ShopEndpoints(Mock);
  UsersEndpoints(Mock);
  TicketsEndpoints(Mock);
  ProductsEndpoints(Mock);
  UserAddressEndpoints(Mock);
  UserOrders1Endpoints(Mock);
  RelatedProductsEndpoints(Mock);
  LayoutEndpoints(Mock);
  CartEndpoints(Mock);
  Mock.onAny().passThrough();
};